# Generated by Django 3.0 on 2019-12-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisanhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
