# Generated by Django 3.0 on 2019-12-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kisanhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisanhub.Locations'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisanhub.Metrics'),
        ),
    ]
